output_dir: ${SCRATCH}/heptrkx/results/agnn_012

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_high_002
    n_train: 57344
    n_valid: 4096
    real_weight: 3
    batch_size: 1
    n_workers: 4

model:
    name: agnn
    input_dim: 3
    n_edge_layers: 4
    n_node_layers: 4
    hidden_dim: 64
    hidden_activation: Tanh
    n_graph_iters: 8
    layer_norm: true
    loss_func: binary_cross_entropy_with_logits

optimizer:
    name: Adam
    learning_rate: 0.001
    weight_decay: 1.e-5
    lr_decay_schedule:
        - {start_epoch: 32, end_epoch: 64, factor: 0.1}

training:
    n_total_epochs: 64
