# Input/output configuration
input_dir: /global/cscratch1/sd/sfarrell/trackml/train_all
#input_dir: /global/cfs/cdirs/m3443/data/trackml-kaggle/train_all
output_dir: /global/cscratch1/sd/sfarrell/heptrkx/data/hitgraphs_high_002
n_files: 8192

# Graph building configuration
selection:
    pt_min: 0. # GeV
    phi_slope_max: 0.0006
    z0_max: 100
    n_phi_sections: 8
    n_eta_sections: 1
    eta_range: [-2, 2]
